import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Playfair Display", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        gold: {
          DEFAULT: "hsl(var(--gold))",
          soft: "hsl(var(--gold-soft))",
          glow: "hsl(var(--gold-glow))",
        },
        rose: { DEFAULT: "hsl(var(--rose))" },
        turquoise: { DEFAULT: "hsl(var(--turquoise))" },
        violet: { DEFAULT: "hsl(var(--violet))" },
        "sky-blue": { DEFAULT: "hsl(var(--sky-blue))" },
        "warm-orange": { DEFAULT: "hsl(var(--warm-orange))" },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "pulse-glow": { "0%, 100%": { opacity: "0.4", transform: "scale(1)" }, "50%": { opacity: "0.85", transform: "scale(1.08)" } },
        "float": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-12px)" } },
        "wave": { "0%": { transform: "scaleY(0.3)" }, "50%": { transform: "scaleY(1)" }, "100%": { transform: "scaleY(0.3)" } },
        "fade-in-up": { from: { opacity: "0", transform: "translateY(20px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "sparkle": { "0%, 100%": { opacity: "0", transform: "scale(0)" }, "50%": { opacity: "1", transform: "scale(1)" } },
        "drift": {
          "0%": { transform: "translate(0,0) rotate(0deg)" },
          "33%": { transform: "translate(10px,-15px) rotate(120deg)" },
          "66%": { transform: "translate(-8px,-8px) rotate(240deg)" },
          "100%": { transform: "translate(0,0) rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "float": "float 4s ease-in-out infinite",
        "wave": "wave 1.2s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.6s ease-out",
        "spin-slow": "spin-slow 8s linear infinite",
        "sparkle": "sparkle 2s ease-in-out infinite",
        "drift": "drift 6s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
